export default {
	getConfigFields() {
		let self = this

		return [
			{
				type: 'static-text',
				id: 'info',
				width: 12,
				label: 'Information',
				value:
					'This module controls the Kiloview CUBE X1 NDI distribution system. It supports matrix routing of NDI sources to outputs, playlists, output locking/favorites and panel templates. When multiple panels exist on the device, set Panel ID or leave it empty to use the first panel.',
			},
			{
				type: 'static-text',
				id: 'hr1',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'textinput',
				id: 'host',
				label: 'Device IP / Host',
				width: 6,
				default: '',
				tooltip: 'IPv4 address, IPv6 address or hostname of the CUBE X1. Do not include the protocol or port.',
			},
			{
				type: 'dropdown',
				id: 'protocol',
				label: 'Protocol',
				width: 3,
				default: 'http',
				choices: [
					{ id: 'http', label: 'HTTP (port: 80)' },
					{ id: 'https', label: 'HTTPS (port: 443)' },
				],
			},
			{
				type: 'number',
				id: 'port',
				label: 'Port',
				width: 3,
				default: 80,
				min: 1,
				max: 65535,
			},
			{
				type: 'textinput',
				id: 'panel_id',
				label: 'Panel ID (optional)',
				width: 3,
				default: '',
				tooltip: 'Leave empty to use the first panel returned by the device.',
			},
			{
				type: 'checkbox',
				id: 'verify_tls',
				label: 'Verify HTTPS Certificate',
				default: false,
				width: 3,
				isVisibleExpression: '$(options:protocol) === "https"',
			},
			{
				type: 'static-text',
				id: 'tlsInfo',
				width: 9,
				label: ' ',
				value:
					'Leave certificate verification disabled for self-signed device certificates. Enable it only when the device presents a trusted certificate.',
				isVisibleExpression: '$(options:protocol) === "https"',
			},
			{
				type: 'static-text',
				id: 'hr2',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'textinput',
				label: 'Username',
				id: 'username',
				width: 3,
				default: 'admin',
			},
			{
				type: 'secret-text',
				label: 'Password',
				id: 'password',
				width: 3,
				default: '',
			},
			{
				type: 'static-text',
				id: 'authInfo',
				width: 6,
				label: ' ',
				value:
					'The CUBE X1 requires a valid user login. The module keeps the session token refreshed automatically. The factory default password is Admin123.',
			},
			{
				type: 'static-text',
				id: 'hr3',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'checkbox',
				id: 'polling',
				label: 'Enable Polling (necessary for feedbacks and variables)',
				default: true,
				width: 3,
				disableAutoExpression: true,
			},
			{
				type: 'number',
				id: 'pollingrate',
				label: 'Polling Rate for Panel State (in ms)',
				default: self.POLLINGRATE,
				width: 3,
				min: 500,
				max: self.POLLINGRATE_MAX,
				isVisibleExpression: '!!$(options:polling)',
			},
			{
				type: 'number',
				id: 'pollingrate_resources',
				label: 'Polling Rate for System Info / Version (in ms)',
				default: self.POLLINGRATE_RESOURCES,
				width: 3,
				min: 1000,
				max: self.POLLINGRATE_RESOURCES_MAX,
				isVisibleExpression: '!!$(options:polling)',
			},
			{
				type: 'number',
				id: 'request_timeout',
				label: 'HTTP Request Timeout (ms)',
				default: self.REQUEST_TIMEOUT_DEFAULT,
				width: 3,
				min: 1000,
				max: 60000,
			},
			{
				type: 'static-text',
				id: 'hr4',
				width: 12,
				label: ' ',
				value: '<hr />',
			},
			{
				type: 'checkbox',
				id: 'verbose',
				label: 'Enable Verbose Logging',
				default: false,
				width: 3,
			},
			{
				type: 'static-text',
				id: 'verboseInfo',
				width: 9,
				label: ' ',
				value:
					'Enabling Verbose Logging will push all incoming and outgoing HTTP requests to the log, which is helpful for debugging.',
			},
		]
	},
}
